# Generated by Django 5.0.7 on 2024-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Сформирован'), ('accepted', 'Принят к работе'), ('processing', 'Находится в работе'), ('shipped', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
    ]
